package GalaxyMerchant.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Ore extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Ore() {
    super(0x733ec1a84f04e04L, 0xa4a37cab3336e413L, 0x3aaa61a28327060bL, "Ore", "r:4c48624a-d2ba-44e1-9e8c-eaa7da7a77b6(GalaxyMerchant.structure)/4227298550853600779");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Gold_0 = new EnumerationDescriptor.MemberDescriptor("Gold", "gold", 0x3aaa61a28327060cL, "r:4c48624a-d2ba-44e1-9e8c-eaa7da7a77b6(GalaxyMerchant.structure)/4227298550853600780");
  private final EnumerationDescriptor.MemberDescriptor myMember_Silver_0 = new EnumerationDescriptor.MemberDescriptor("Silver", "silver", 0x3aaa61a28327060dL, "r:4c48624a-d2ba-44e1-9e8c-eaa7da7a77b6(GalaxyMerchant.structure)/4227298550853600781");
  private final EnumerationDescriptor.MemberDescriptor myMember_Iron_0 = new EnumerationDescriptor.MemberDescriptor("Iron", "iron", 0x3aaa61a28327060eL, "r:4c48624a-d2ba-44e1-9e8c-eaa7da7a77b6(GalaxyMerchant.structure)/4227298550853600782");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x733ec1a84f04e04L, 0xa4a37cab3336e413L, 0x3aaa61a28327060bL, 0x3aaa61a28327060cL, 0x3aaa61a28327060dL, 0x3aaa61a28327060eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Gold_0, myMember_Silver_0, myMember_Iron_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Iron_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Gold":
        return myMember_Gold_0;
      case "Silver":
        return myMember_Silver_0;
      case "Iron":
        return myMember_Iron_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
