package GalaxyMerchant.runtime;

/*Generated by MPS */

import java.util.List;

public class ConversionAsk implements Visitable {

  private Ore ore;
  private List<String> names;

  public ConversionAsk(Ore ore, List<String> names) {
    this.ore = ore;
    this.names = names;
  }

  public Ore getOre() {
    return this.ore;
  }

  public List<String> getNames() {
    return this.names;
  }

  public void accept(EvalVisitor visitor) {
    visitor.visit(this);
  }

}
