package GalaxyMerchant.runtime;

/*Generated by MPS */

import java.util.List;

public class ConversionDef implements Visitable {

  private Ore ore;
  private int credits;
  private List<String> amount;

  public ConversionDef(Ore ore, int credits, List<String> amount) {
    this.ore = ore;
    this.credits = credits;
    this.amount = amount;
  }

  public Ore getOre() {
    return this.ore;
  }

  public int getCredits() {
    return this.credits;
  }

  public List<String> getAmount() {
    return this.amount;
  }
  public void accept(EvalVisitor visitor) {
    visitor.visit(this);
  }


}
