package GalaxyMerchant.runtime;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class EvalVisitor {
  private Env env;

  public EvalVisitor() {
    this.env = new Env();
  }

  public void visit(Assign assgn) {
    this.env.addBinding(assgn.getName(), assgn.getNum());
  }

  public void visit(ValueAsk vlAsk) {
    List<Number> nums = ListSequence.fromList(new ArrayList<Number>(ListSequence.fromList(vlAsk.getNames()).count()));
    for (String name : vlAsk.getNames()) {
      ListSequence.fromList(nums).addElement(env.lookupName(name));
    }
    int value = env.sum(nums);
    System.out.println("Total value is " + value);

    return;
  }

  public void visit(ConversionAsk cnvAsk) {
    List<Number> nums = ListSequence.fromList(new ArrayList<Number>(ListSequence.fromList(cnvAsk.getNames()).count()));
    for (String name : cnvAsk.getNames()) {
      ListSequence.fromList(nums).addElement(env.lookupName(name));
    }
    int value = env.sum(nums);

    float result = env.lookupConversion(cnvAsk.getOre()) * ((float) value);

    // TODO: Better message
    System.out.println(result);
  }

  public void visit(ConversionDef cnvDef) {
    return;
  }
}
