package GalaxyMerchant.runtime;

/*Generated by MPS */

import java.util.List;

public class ValueAsk implements Visitable {

  private List<String> names;

  public ValueAsk(List<String> nms) {
    this.names = nms;
  }

  public List<String> getNames() {
    return this.names;
  }

  public void accept(EvalVisitor visitor) {
    visitor.visit(this);
  }

}
